apiVersion: v1
entries:
  cert-manager-webhook-domeneshop:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2026-05-21T11:14:07.9191224+02:00"
    description: cert-manager webhook for Domeneshop
    digest: fc433264e04c60b280e8531c5145a4f5b97591828eb505529c551bf39d0a201d
    icon: https://domene.shop/svg/logo-no.svg
    name: cert-manager-webhook-domeneshop
    urls:
    - https://littformyekode.github.io/cert-manager-webhook-domeneshop/cert-manager-webhook-domeneshop-1.0.0.tgz
    version: 1.0.0
generated: "2026-05-21T11:14:07.9137449+02:00"
